services:

  postgres:
    image: postgres:15.0-alpine
    container_name: blackjack_bot_db
    volumes:
      - postgres_data_bjb:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}  # может убрать?
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: blackjack_bot_rabbitmq
  #   restart: always
  #   ports:
  #     - 15672:15672
  #     - 5673:5672
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  app:
    build: ./
    image: blackjack_bot_app
    # image: earlinn/blackjackbot_app:v.01
    container_name: blackjack_bot_app
    env_file:
      - ./.env
    command: >
      sh -c "sleep 5 &&
             python -m alembic upgrade head &&
             export BOT_TOKEN=${BOT_TOKEN} &&
             python main.py"
    restart: always
    depends_on:
      postgres:
        condition: service_started
      # rabbitmq:
      #   condition: service_healthy
  
  djangoadmin:
    build: ./djangoadmin
    image: blackjack_bot_djangoadmin
    # image: earlinn/blackjackbot_djangoadmin:v.01
    container_name: blackjack_bot_djangoadmin
    volumes:
      - static_value:/app/staticdjango/
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn djangoadmin.wsgi:application --bind 0:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_started

  nginx:
    image: nginx:1.25.3-alpine
    container_name: blackjack_bot_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticdjango
    restart: always
    depends_on:
      - app

volumes:
  postgres_data_bjb:
  static_value:
 
