services:

  # приходится называть контейнер с БД localhost вместо db, т.к. workflow
  # GitHub Actions в сервисе postgres (используем для миграций alembic) по
  # умолчанию POSTGRES_HOST=localhost, и непонятно, как это изменить на свое
  # собственное значение. Поэтому в файле etc/config.yml приходится тоже
  # сохранять host: localhost, чтобы и workflow выпонялся, и проект в докере
  # поднимался
  localhost:
    image: postgres:15.0-alpine
    container_name: blackjack_bot_db
    volumes:
      - postgres_data_bjb:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
  
  app:
    build: ./
    image: blackjack_bot_app
    container_name: blackjack_bot_app
    env_file:
      - ./.env
    command: >
      sh -c "sleep 5 &&
             python -m alembic upgrade head &&
             export BOT_TOKEN=${BOT_TOKEN} &&
             python main.py"
    restart: always
    depends_on:
      - localhost
  
  nginx:
    image: nginx:1.25.3-alpine
    container_name: blackjack_bot_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app

volumes:
  postgres_data_bjb:
 
