"""Add first_name in players table

Revision ID: e44b8e0d5d9d
Revises: 81546d951a1a
Create Date: 2024-05-24 11:06:30.849628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44b8e0d5d9d'
down_revision: Union[str, None] = '81546d951a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('first_name', sa.String(), nullable=True))
    op.alter_column('players', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###
