"""create games table

Revision ID: 34d6a9fb3bb7
Revises: 7fe51aa76be1
Create Date: 2024-05-09 19:42:17.010717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d6a9fb3bb7'
down_revision: Union[str, None] = '7fe51aa76be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'INTERRUPTED', 'CANCELED', name='gamestatus'), nullable=False),
    sa.Column('stage', sa.Enum('WAITING_FOR_PLAYERS_TO_JOIN', 'BETTING', 'PLAYERHIT', 'DILLERHIT', 'SUMMARIZING', name='gamestage'), nullable=False),
    sa.Column('diller_cards', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.execute("DROP TYPE gamestatus")
    op.execute("DROP TYPE gamestage")
    # ### end Alembic commands ###
