"""create gameplays table

Revision ID: 39e2544c8942
Revises: 34d6a9fb3bb7
Create Date: 2024-05-09 19:43:28.981985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e2544c8942'
down_revision: Union[str, None] = '34d6a9fb3bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameplays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_bet', sa.Integer(), nullable=False),
    sa.Column('player_status', sa.Enum('BETTING', 'TAKING', 'STANDING', 'EXCEEDED', 'LOST', 'WON', name='playerstatus'), nullable=False),
    sa.Column('player_cards', sa.ARRAY(sa.String()), nullable=False),
    sa.CheckConstraint('player_bet > 0', name='positive_player_bet_constraint'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='game_player_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameplays')
    op.execute("DROP TYPE playerstatus")
    # ### end Alembic commands ###
