"""create games table

Revision ID: d651eee5642e
Revises: 5af2bbc7e7fd
Create Date: 2024-05-09 12:25:46.648625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd651eee5642e'
down_revision: Union[str, None] = '5af2bbc7e7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'INTERRUPTED', name='gamestatus'), nullable=False),
    sa.Column('stage', sa.Enum('BETTING', 'PLAYERHIT', 'DILLERHIT', 'SUMMARIZING', name='gamestage'), nullable=False),
    sa.Column('turn_player_id', sa.Integer(), nullable=True),
    sa.Column('diller_cards', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['turn_player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.execute("DROP TYPE gamestatus")
    op.execute("DROP TYPE gamestage")
    # ### end Alembic commands ###
