"""create games and gameplays

Revision ID: d284f4f8936c
Revises: 5af2bbc7e7fd
Create Date: 2024-05-08 23:34:28.709565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd284f4f8936c'
down_revision: Union[str, None] = '5af2bbc7e7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'INTERRUPTED', name='gamestatus'), nullable=False),
    sa.Column('stage', sa.Enum('BETTING', 'PLAYERHIT', 'DILLERHIT', 'SUMMARIZING', name='gamestage'), nullable=False),
    sa.Column('turn_player_id', sa.Integer(), nullable=False),
    sa.Column('diller_cards', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameplays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_bet', sa.Integer(), nullable=False),
    sa.Column('player_status', sa.Enum('BETTING', 'TAKING', 'STANDING', 'EXCEEDED', 'LOST', 'WON', name='playerstatus'), nullable=False),
    sa.Column('player_cards', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='game_player_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameplays')
    op.drop_table('games')
    op.execute("DROP TYPE gamestatus")
    op.execute("DROP TYPE gamestage")
    op.execute("DROP TYPE playerstatus")
    # ### end Alembic commands ###
