debug: true
web:
  host: 127.0.0.1
  port: 8000

sentry:
  dsn:
  env: dev

store: {}

session:
  key: U-7ifh1kpIhDOBD8jodP0f3zx5Acez8EpVm3VKjPNWc=
admin:
  email: admin@admin.com
  password: admin
database:
  host: postgres  # поменять на localhost для локального запуска вне Docker
  port: 5432
  user: postgres
  password: postgres  # поменять на свой пароль для локального запуска вне Docker
  database: postgres  # поменять на black_jack_bot для локального запуска вне Docker
rabbitmq:
  host: rabbitmq  # поменять на localhost для локального запуска вне Docker
  user: guest
  password: guest
