debug: true
web:
  host: 127.0.0.1
  port: 8000

sentry:
  dsn:
  env: dev

store: {}

session:
  key: U-7ifh1kpIhDOBD8jodP0f3zx5Acez8EpVm3VKjPNWc=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost  # поменять на localhost для локального запуска вне Docker Compose
  port: 5432
  user: postgres
  password: postgres
  database: postgres  # поменять на black_jack_bot для локального запуска
bot:
  token: token
  group_id: 1
