name: Check homework
on: [push]
jobs:
  lint_and_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install ruff
        run: pip install ruff==0.4.2
      - run: ruff format --check && ruff check --no-fix

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Wait for PostgreSQL
      #   run: |
      #     for i in {1..30}; do
      #       nc -z db 5432 && echo "Postgres is up" && break
      #       echo "Waiting for postgres..."
      #       sleep 1
      #     done

      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres

      - name: Pytest tests
        run: pytest
